name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - '✨ goal: improvement'
      - '⭐ goal: addition'
  - title: '🐛 Bug Fixes'
    labels:
      - '🛠 goal: fix'
  - title: '🧰 Maintenance'
    labels: 
      - 'chore'
      - '🛠 goal: refactor'     
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES