name: 🌱 Project Addition
description: Add a new project to the list
title: 'chore: project addition by '
labels: ['projects addition', '🚦status: awaiting triage', 'good first issue']
body:
  - type: textarea
    id: project-add
    attributes:
      label: Add a new project to the list
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: 'Record'
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

        - label: I'm a GSSoC'23 contributor

        - label: I want to work on this issue
        
        - label: My project has contribution guidelines
          required: true
        
        - label: My project has a Code of conduct
          required: true
          
        - label: My project has README
          required: true
        
        - label: My project has a License
          required: true
                
          
