name: 🌱 Project Addition
description: Add a new project to the list
title: "chore: project addition by "
labels:
  [
    "projects addition",
    "🚦status: awaiting triage",
    "good first issue",
    "🟩 priority: low",
  ]
body:
  - type: textarea
    id: project-add
    attributes:
      label: Add a new project to the list
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: "Record"
      options:
        - label: I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
          required: true

        - label: I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
          required: true

        - label: I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
          required: true

        - label: I want to work on this issue
