name: 🌱 Project Addition
description: Add a new project to the list
title: "data: project addition by "
labels: ["🌱 chore: projects addition", "👍  status: approved", "gssoc23"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this translate documentation update template!
  - type: textarea
    id: project-add
    attributes:
      label: Add a new project to the list
      value: " I want to add a new project to the list "
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
