import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head> <meta charSet="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, user-scalable=no" />
    {/* <!-- For SEO --> */}
    <meta
      name="description"
      content="ProjectsHut is an open-source platform for sharing and promoting projects. It fosters collaboration and innovation among creative individuals, providing an easy-to-use interface for publishing and connecting with like-minded users."
    />
    <meta
      name="keywords"
      content="ProjectsHut, open source, good-first-issue, how to contribute to projectshut, web application, share projects, promote projects, publish projects, community, ideas, innovation, developer, connect with others"
    />
    <meta name="robots" content="index, follow" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="language" content="English" />
    <meta name="revisit-after" content="1 days" />
    <meta name="author" content="Priyankar Pal" />

   
    <meta name="title" content="ProjectsHut" />

    
    <meta property="og:type" content="website" />
    <meta property="og:url" content="https://projectshut.vercel.app/" />
    <meta property="og:title" content="ProjectsHut" />
    <meta
      property="og:description"
      content="ProjectsHut is an open-source platform for sharing and promoting projects. It fosters collaboration and innovation among creative individuals, providing an easy-to-use interface for publishing and connecting with like-minded users."
    />
    <meta
      property="og:image"
      content="https://user-images.githubusercontent.com/88102392/243149476-6d99804f-14df-420b-9a4d-486953d59b11.png"
    />

     {/* Twitter */}
    <meta property="twitter:card" content="summary_large_image" />
    <meta property="twitter:url" content="https://projectshut.vercel.app/" />
    <meta property="twitter:title" content="ProjectsHut" />
    <meta
      property="twitter:description"
      content="ProjectsHut is an open-source platform for sharing and promoting projects. It fosters collaboration and innovation among creative individuals, providing an easy-to-use interface for publishing and connecting with like-minded users."
    />
    <meta
      property="twitter:image"
      content="https://user-images.githubusercontent.com/88102392/243149476-6d99804f-14df-420b-9a4d-486953d59b11.png"
    />


    <link href="https://fonts.googleapis.com/css2?family=Inter" rel="stylesheet" />
    <title>ProjectsHut - A Place to find lots of cool Projects</title>

    <script async src="https://www.googletagmanager.com/gtag/js?id=G-ZYVRV0PJ87"></script>
    </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
