name: Greetings

on:
  pull_request_target:
  issues:
  
jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: Check for first-time contributor
      uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for creating your first issue in ProjectsHut, @${{ github.actor }}! 🎉 I appreciate your contribution and look forward to hearing more from you. If you need any help or guidance, feel free to ask!"
        pr-message: "Congratulations, @${{ github.actor }}! 🎉 You just created your first pull request in ProjectsHut. I'm excited to review it and work with you to make it the best it can be. If you have any questions or need any assistance, don't hesitate to reach out."
