---
name: "ProjectsHut Labeler"

on:
  workflow_dispatch:
  pull_request:
    branches: ["main", "dev"]

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    steps:
      - name: Labeler
        uses: actions/labeler@0776a679364a9a16110aac8d0f40f5e11009e327 # v4.0.4
        with:
          configuration-path: .github/labeler.yaml
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
