name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Node.js and Yarn
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        cache: 'yarn'
      run: |
        yarn install --frozen-lockfile
    - name: Get latest tag
      id: latest_tag
      uses: actions/github-script@v4
      with:
        script: |
          const tags = await github.repos.listTags({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          return tags.data[0].name;
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
    - name: Get commit log
      id: commit_log
      uses: actions/github-script@v4
      with:
        script: |
          const commits = await github.repos.compareCommits({
            owner: context.repo.owner,
            repo: context.repo.repo,
            base: '${{ steps.latest_tag.outputs.result }}',
            head: context.sha,
          });
          return commits.data.commits.map((commit) => `- ${commit.commit.message}`).join('\n');
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.6
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        tag_name: ${{ steps.latest_tag.outputs.result }}
        release_name: Release ${{ steps.latest_tag.outputs.result }}
        body: |
          ### Changes
          ${steps.commit_log.outputs.result}
        draft: false
        prerelease: false
