name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '0 * * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v7
        with:
          stale-issue-message: "This issue hasn't had any activity in the past 7 days and will be closed as stale. Please feel free to reopen it if you still need assistance."
          stale-pr-message: " This pull request hasn't had any activity in the past 7 days and will be closed as stale. Please feel free to reopen it if you still want to contribute"
          stale-issue-label: 'no-issue-activity'
          exempt-issue-labels: 'awaiting-approval,work-in-progress'
          stale-pr-label: 'no-pr-activity'
          exempt-pr-labels: 'awaiting-approval,work-in-progress'
          only-labels: 'awaiting-feedback,awaiting-answers'
          days-before-issue-stale: 7
          days-before-pr-stale: 7
          days-before-issue-close: 2
          days-before-pr-close: 2
          exempt-all-pr-milestones: true
          exempt-all-pr-assignees: true
          
